// このファイルは npm run generate:puzzles で生成されます。
// 手作業で問題配置を編集しないでください。

import type { VerifiedPuzzle } from './types';

export const PUZZLES: readonly VerifiedPuzzle[] = [
  {
    "puzzleId": "master-r1-g1-d1-mt-0001-0",
    "displayNumber": 1,
    "mode": "master",
    "designFamily": "trap-cascade",
    "seed": "mt-0001-0",
    "ruleVersion": "1.0.0",
    "generatorVersion": "1.0.0",
    "difficultyVersion": "1.0.0",
    "initialBoard": {
      "width": 9,
      "cells": [
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        6,
        0,
        6,
        0,
        2,
        0,
        0,
        6,
        0,
        0,
        6,
        0,
        7,
        7,
        0,
        2,
        0
      ],
      "logicalLength": 72
    },
    "initialRows": 8,
    "initialBoardHash": "1bbd4c25",
    "additionsAllowed": 0,
    "initialAliveCount": 20,
    "initialMoveCount": 12,
    "solutionStatus": "SOLVED",
    "bestKnownSolutionLength": 10,
    "provenOptimal": false,
    "minimumAdditions": 0,
    "minimumAdditionsProven": true,
    "nodesExpanded": 10,
    "averageBranching": 6.5,
    "maximumBranching": 12,
    "forcedMoveRatio": 0.2,
    "trapMoveCount": 2,
    "estimatedSolutionCount": 10,
    "maximumRowsDuringSolution": 8,
    "phaseDifficulty": {
      "early": 100,
      "middle": 75,
      "late": 45
    },
    "difficultyScore": 71,
    "structureSignature": "a314a689",
    "reviewed": true
  },
  {
    "puzzleId": "master-r1-g1-d1-mt-0002--pzg20d",
    "displayNumber": 2,
    "mode": "master",
    "designFamily": "double-trap",
    "seed": "mt-0002--pzg20d",
    "ruleVersion": "1.0.0",
    "generatorVersion": "1.0.0",
    "difficultyVersion": "1.0.0",
    "initialBoard": {
      "width": 9,
      "cells": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        5,
        0,
        5,
        0,
        1,
        0,
        0,
        5,
        0,
        0,
        5,
        0,
        6,
        6,
        0,
        1,
        0,
        2,
        0,
        0,
        6,
        0,
        2,
        0,
        2,
        0,
        0,
        6,
        0,
        5,
        5,
        0,
        2,
        0,
        0
      ],
      "logicalLength": 81
    },
    "initialRows": 9,
    "initialBoardHash": "676f83ff",
    "additionsAllowed": 0,
    "initialAliveCount": 26,
    "initialMoveCount": 16,
    "solutionStatus": "SOLVED",
    "bestKnownSolutionLength": 13,
    "provenOptimal": false,
    "minimumAdditions": 0,
    "minimumAdditionsProven": true,
    "nodesExpanded": 13,
    "averageBranching": 8.15,
    "maximumBranching": 16,
    "forcedMoveRatio": 0.1538,
    "trapMoveCount": 0,
    "estimatedSolutionCount": 16,
    "maximumRowsDuringSolution": 9,
    "phaseDifficulty": {
      "early": 100,
      "middle": 83,
      "late": 47
    },
    "difficultyScore": 68,
    "structureSignature": "a11831f9",
    "reviewed": true
  },
  {
    "puzzleId": "master-r1-g1-d1-mt-0003-j0w6g2",
    "displayNumber": 3,
    "mode": "master",
    "designFamily": "add-one",
    "seed": "mt-0003-j0w6g2",
    "ruleVersion": "1.0.0",
    "generatorVersion": "1.0.0",
    "difficultyVersion": "1.0.0",
    "initialBoard": {
      "width": 9,
      "cells": [
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        3,
        5,
        9,
        4,
        2,
        4,
        9,
        5
      ],
      "logicalLength": 89
    },
    "initialRows": 10,
    "initialBoardHash": "377e7cec",
    "additionsAllowed": 1,
    "initialAliveCount": 26,
    "initialMoveCount": 10,
    "solutionStatus": "SOLVED",
    "bestKnownSolutionLength": 18,
    "provenOptimal": false,
    "minimumAdditions": 1,
    "minimumAdditionsProven": true,
    "nodesExpanded": 18,
    "averageBranching": 4.83,
    "maximumBranching": 10,
    "forcedMoveRatio": 0.1667,
    "trapMoveCount": 0,
    "estimatedSolutionCount": 10,
    "maximumRowsDuringSolution": 10,
    "phaseDifficulty": {
      "early": 91,
      "middle": 67,
      "late": 58
    },
    "difficultyScore": 74,
    "structureSignature": "3ce39595",
    "reviewed": true
  },
  {
    "puzzleId": "master-r1-g1-d1-mt-0004--6yjvkb",
    "displayNumber": 4,
    "mode": "master",
    "designFamily": "add-two",
    "seed": "mt-0004--6yjvkb",
    "ruleVersion": "1.0.0",
    "generatorVersion": "1.0.0",
    "difficultyVersion": "1.0.0",
    "initialBoard": {
      "width": 9,
      "cells": [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        2,
        4,
        5,
        1
      ],
      "logicalLength": 94
    },
    "initialRows": 11,
    "initialBoardHash": "0ca966d7",
    "additionsAllowed": 2,
    "initialAliveCount": 24,
    "initialMoveCount": 10,
    "solutionStatus": "SOLVED",
    "bestKnownSolutionLength": 15,
    "provenOptimal": false,
    "minimumAdditions": 1,
    "minimumAdditionsProven": true,
    "nodesExpanded": 418,
    "averageBranching": 4.53,
    "maximumBranching": 10,
    "forcedMoveRatio": 0.2667,
    "trapMoveCount": 10,
    "estimatedSolutionCount": 1,
    "maximumRowsDuringSolution": 11,
    "phaseDifficulty": {
      "early": 97,
      "middle": 63,
      "late": 49
    },
    "difficultyScore": 85,
    "structureSignature": "2ad5ec9f",
    "reviewed": true
  },
  {
    "puzzleId": "master-r1-g1-d1-mt-0005--wzbs58",
    "displayNumber": 5,
    "mode": "master",
    "designFamily": "add-three",
    "seed": "mt-0005--wzbs58",
    "ruleVersion": "1.0.0",
    "generatorVersion": "1.0.0",
    "difficultyVersion": "1.0.0",
    "initialBoard": {
      "width": 9,
      "cells": [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        5,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        8,
        5
      ],
      "logicalLength": 101
    },
    "initialRows": 12,
    "initialBoardHash": "f3dda4e3",
    "additionsAllowed": 3,
    "initialAliveCount": 24,
    "initialMoveCount": 11,
    "solutionStatus": "SOLVED",
    "bestKnownSolutionLength": 16,
    "provenOptimal": false,
    "minimumAdditions": 1,
    "minimumAdditionsProven": true,
    "nodesExpanded": 3906,
    "averageBranching": 5.25,
    "maximumBranching": 11,
    "forcedMoveRatio": 0.1875,
    "trapMoveCount": 11,
    "estimatedSolutionCount": 1,
    "maximumRowsDuringSolution": 12,
    "phaseDifficulty": {
      "early": 100,
      "middle": 64,
      "late": 52
    },
    "difficultyScore": 88,
    "structureSignature": "74451e5c",
    "reviewed": true
  }
];
